services:
  app:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
  worker:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
  postgres:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
  redis:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
